<?php

namespace AppBundle\Repository;

/**
 * LoisirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoisirRepository extends \Doctrine\ORM\EntityRepository
{
}
